#include "utils.h"

#include <stddef.h>

#include "defs.h" // for ARR_SIZE

#define STATUS_TO_NAME(x) {x,#x}

static const struct npp_status_map_t {
        NppStatus rc;
        const char *name;
} npp_status_mapping[] = {
        STATUS_TO_NAME(NPP_NOT_SUPPORTED_MODE_ERROR),
        STATUS_TO_NAME(NPP_INVALID_HOST_POINTER_ERROR),
        STATUS_TO_NAME(NPP_INVALID_DEVICE_POINTER_ERROR),
        STATUS_TO_NAME(NPP_LUT_PALETTE_BITSIZE_ERROR),
        STATUS_TO_NAME(NPP_ZC_MODE_NOT_SUPPORTED_ERROR),
        STATUS_TO_NAME(NPP_NOT_SUFFICIENT_COMPUTE_CAPABILITY),
        STATUS_TO_NAME(NPP_TEXTURE_BIND_ERROR),
        STATUS_TO_NAME(NPP_WRONG_INTERSECTION_ROI_ERROR),
        STATUS_TO_NAME(NPP_HAAR_CLASSIFIER_PIXEL_MATCH_ERROR),
        STATUS_TO_NAME(NPP_MEMFREE_ERROR),
        STATUS_TO_NAME(NPP_MEMSET_ERROR),
        STATUS_TO_NAME(NPP_MEMCPY_ERROR),
        STATUS_TO_NAME(NPP_ALIGNMENT_ERROR),
        STATUS_TO_NAME(NPP_CUDA_KERNEL_EXECUTION_ERROR),
        STATUS_TO_NAME(NPP_ROUND_MODE_NOT_SUPPORTED_ERROR),
        STATUS_TO_NAME(NPP_QUALITY_INDEX_ERROR),
        STATUS_TO_NAME(NPP_RESIZE_NO_OPERATION_ERROR),
        STATUS_TO_NAME(NPP_OVERFLOW_ERROR),
        STATUS_TO_NAME(NPP_NOT_EVEN_STEP_ERROR),
        STATUS_TO_NAME(NPP_HISTOGRAM_NUMBER_OF_LEVELS_ERROR),
        STATUS_TO_NAME(NPP_LUT_NUMBER_OF_LEVELS_ERROR),
        STATUS_TO_NAME(NPP_CORRUPTED_DATA_ERROR),
        STATUS_TO_NAME(NPP_CHANNEL_ORDER_ERROR),
        STATUS_TO_NAME(NPP_ZERO_MASK_VALUE_ERROR),
        STATUS_TO_NAME(NPP_QUADRANGLE_ERROR),
        STATUS_TO_NAME(NPP_RECTANGLE_ERROR),
        STATUS_TO_NAME(NPP_COEFFICIENT_ERROR),
        STATUS_TO_NAME(NPP_NUMBER_OF_CHANNELS_ERROR),
        STATUS_TO_NAME(NPP_COI_ERROR),
        STATUS_TO_NAME(NPP_DIVISOR_ERROR),
        STATUS_TO_NAME(NPP_CHANNEL_ERROR),
        STATUS_TO_NAME(NPP_STRIDE_ERROR),
        STATUS_TO_NAME(NPP_ANCHOR_ERROR),
        STATUS_TO_NAME(NPP_MASK_SIZE_ERROR),
        STATUS_TO_NAME(NPP_RESIZE_FACTOR_ERROR),
        STATUS_TO_NAME(NPP_INTERPOLATION_ERROR),
        STATUS_TO_NAME(NPP_MIRROR_FLIP_ERROR),
        STATUS_TO_NAME(NPP_MOMENT_00_ZERO_ERROR),
        STATUS_TO_NAME(NPP_THRESHOLD_NEGATIVE_LEVEL_ERROR),
        STATUS_TO_NAME(NPP_THRESHOLD_ERROR),
        STATUS_TO_NAME(NPP_CONTEXT_MATCH_ERROR),
        STATUS_TO_NAME(NPP_FFT_FLAG_ERROR),
        STATUS_TO_NAME(NPP_FFT_ORDER_ERROR),
        STATUS_TO_NAME(NPP_STEP_ERROR),
        STATUS_TO_NAME(NPP_SCALE_RANGE_ERROR),
        STATUS_TO_NAME(NPP_DATA_TYPE_ERROR),
        STATUS_TO_NAME(NPP_OUT_OFF_RANGE_ERROR),
        STATUS_TO_NAME(NPP_DIVIDE_BY_ZERO_ERROR),
        STATUS_TO_NAME(NPP_MEMORY_ALLOCATION_ERR),
        STATUS_TO_NAME(NPP_NULL_POINTER_ERROR),
        STATUS_TO_NAME(NPP_RANGE_ERROR),
        STATUS_TO_NAME(NPP_SIZE_ERROR),
        STATUS_TO_NAME(NPP_BAD_ARGUMENT_ERROR),
        STATUS_TO_NAME(NPP_NO_MEMORY_ERROR),
        STATUS_TO_NAME(NPP_NOT_IMPLEMENTED_ERROR),
        STATUS_TO_NAME(NPP_ERROR),
        STATUS_TO_NAME(NPP_ERROR_RESERVED),
        STATUS_TO_NAME(NPP_NO_ERROR),
        STATUS_TO_NAME(NPP_NO_OPERATION_WARNING),
        STATUS_TO_NAME(NPP_DIVIDE_BY_ZERO_WARNING),
        STATUS_TO_NAME(NPP_AFFINE_QUAD_INCORRECT_WARNING),
        STATUS_TO_NAME(NPP_WRONG_INTERSECTION_ROI_WARNING),
        STATUS_TO_NAME(NPP_WRONG_INTERSECTION_QUAD_WARNING),
        STATUS_TO_NAME(NPP_DOUBLE_SIZE_WARNING),
        STATUS_TO_NAME(NPP_MISALIGNED_DST_ROI_WARNING),
};

const char *npp_status_to_str(NppStatus rc) {
        for (unsigned i = 0; i < ARR_SIZE(npp_status_mapping); ++i) {
                if (npp_status_mapping[i].rc == rc) {
                        return npp_status_mapping[i].name;
                }
        }
        return "(unknown)";
}
